### ISSUE TITLE
Termos de Uso

### ISSUE THREAD

**Issue by Pamela-Carvalho** [ifspcodelab/portal-eventos-sci#19]
** Tarefas **

- [ ] Redigir os termos de uso do Portal.
- [ ] Criar página para exibição dos termos de uso.

** Critérios de aceitação **

- [ ] Interface de usuário responsiva.
- [ ] Acesso público (sem necessidade de autenticação/autorização).
- [ ] Funcional (pronto para uso).
