### ISSUE TITLE
Calendário de Eventos

### ISSUE THREAD

**Issue by vagnermgoncalves** [ifspcodelab/portal-eventos-sci#7]
** Tarefas **

- [ ] Implementar seção de calendário.
- [ ] Integrar agenda de eventos com o calendário.

** Critérios de aceitação **

- [ ] Interface de usuário responsiva.
- [ ] Acesso público (sem necessidade de autenticação/autorização).
- [ ] Funcional (pronto para uso).
